### ISSUE TITLE
EOL error when using runserver  on windows

### ISSUE THREAD

**Issue by lapsed-pacifist** [Chris7/djangui#21]
I get the following when I do `python manage.py runserver`:

```
[23/Jun/2015 15:10:54]"GET /admin HTTP/1.1" 500 59
Traceback (most recent call last):
  File "C:\Anaconda\Lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "D:\Repositories\Insights Server 2\ENV\lib\site-packages\django\contrib\staticfiles\handlers.
py", line 63, in __call__
    return self.application(environ, start_response)
  File "D:\Repositories\Insights Server 2\ENV\lib\site-packages\django\core\handlers\wsgi.py", line
170, in __call__
    self.load_middleware()
  File "D:\Repositories\Insights Server 2\ENV\lib\site-packages\django\core\handlers\base.py", line
50, in load_middleware
    mw_class = import_string(middleware_path)
  File "D:\Repositories\Insights Server 2\ENV\lib\site-packages\django\utils\module_loading.py", lin
e 26, in import_string
    module = import_module(module_path)
  File "C:\Anaconda\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "D:\Repositories\Insights Server 2\Insights\Insights\middleware.py", line 9
    sys.stderr.write('{}'.format('
                                 ^
SyntaxError: EOL while scanning string literal
```

The file in question should be edited from:

```
__author__ = 'chris'
import traceback
import sys

class ProcessExceptionMiddleware(object):
    def process_response(self, request, response):
        if response.status_code != 200:
            try:
                sys.stderr.write('{}'.format(''
'.join(traceback.format_exc())))
            except AttributeError:
                pass
        return response
```

to 

```
__author__ = 'chris'
import traceback
import sys

class ProcessExceptionMiddleware(object):
    def process_response(self, request, response):
        if response.status_code != 200:
            try:
                sys.stderr.write('{}'.format(''.join(traceback.format_exc())))
            except AttributeError:
                pass
        return response
```

**Comment by Chris7** [comment]
That's an issue with using six, which is now stripping the newline from the project templating -- you can see in conf/project_template/middleware.py it's a \n. Odd it is only now occurring. The six translation isn't not needed so I pushed a fix for this. 

Thanks for your report and sorry for this inconvenience.

**Comment by Chris7** [comment]
Latest version on pip should solve these.
