### ISSUE TITLE
Install issue: relation "djangui_script" does not exist

### ISSUE THREAD

**Issue by dethpickle** [Chris7/djangui#9]
I'm trying to install this into an existing django 1.7 (django-autoslug==1.8.0, django-celery==3.1.16) and failing when trying to migrate the database in.

```
$ python manage.py makemigrations djangui
/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/request/managers.py:95: RemovedInDjango18Warning: `RequestManager.get_query_set` method should be renamed `get_queryset`.
  class RequestManager(models.Manager):

Unable to load scripts:
Traceback (most recent call last):
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/djangui/apps.py", line 13, in ready
    utils.load_scripts()
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/djangui/backend/utils.py", line 84, in load_scripts
    scripts = Script.objects.count()
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/models/query.py", line 338, in count
    return self.query.get_count(using=self.db)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 424, in get_count
    number = obj.get_aggregation(using=using)[None]
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 390, in get_aggregation
    result = query.get_compiler(using).execute_sql(SINGLE)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "djangui_script" does not exist
LINE 1: SELECT COUNT(*) FROM "djangui_script"
                             ^


Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 57, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 241, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/home/dethpickle/.virtualenvs/tsutilweb/local/lib/python2.7/site-packages/django/db/migrations/graph.py", line 42, in add_dependency
    raise KeyError("Migration %s dependencies references nonexistent parent node %r" % (migration, parent))
KeyError: u"Migration djangui.0001_initial dependencies references nonexistent parent node (u'auth', u'0006_require_contenttypes_0002')"
```

The djangui_script seems to be an element inside the utils.py, but I'm not sure where that's falling apart.

I've slogged my way through some deep stuff, but I'll confess that my knowledge is pretty slim.  I could be missing something pretty elementary.  But the instructions seem very straight forward and unambiguous.  All of the configuration parameters seem optional...  I'm a bit at a loss.

Any simple steps you'd recommend?  Thanks!

**Comment by Chris7** [comment]
It's because I made the migration with Django1.8, which has that migrations. I'll delete that dependency in the file and update since it shouldn't matter. Thanks for the report.

**Comment by dethpickle** [comment]
Confirmed your current master resolves this issue.  Both make migration and migrate function on django 1.7.   Thanks!
